### ISSUE TITLE
Error with happymh

### ISSUE THREAD

**Issue by lekoOwO** [ThePhaseless/Byparr#138]
### I've completed the following steps:

- [x] Read Loop Warning on Readme
- [x] Done the troubleshooting from Readme
- [x] Checked if such issue already exists

### OS

Docker

### Platform and model

VM

### Architecture

AMD64

### Website

https://m.happymh.com/v2.0/apis/manga/ssearch

### Docker Compose config

```yaml
services:
  byparr:
    image: ghcr.io/thephaseless/byparr:main
    environment:
      - TZ=Asia/Taipei
    restart: unless-stopped
```

### Describe the bug

The log gives
```
byparr-1  | /app/.venv/lib/python3.13/site-packages/pyautogui/_pyautogui_x11.py:284: SyntaxWarning: invalid escape sequence '\e'
byparr-1  |   '\e': _display.keysym_to_keycode(Xlib.XK.string_to_keysym('Escape')),
byparr-1  | INFO:     From: 172.18.0.2 at 2025-04-04 02:11:23: https://m.happymh.com/v2.0/apis/manga/ssearch
byparr-1  | INFO:     Clicked captcha
byparr-1  | INFO:     Failed https://m.happymh.com/v2.0/apis/manga/ssearch in 9.76s
byparr-1  | INFO:     172.18.0.2:52234 - "POST /v1 HTTP/1.1" 500 Internal Server Error
```

And i have no clue why is it failed

### Additional context

The HTML of page [https://m.happymh.com/v2.0/apis/manga/ssearch](https://github.com/user-attachments/files/19592442/happymh.txt) is provided in case it is needed for debugging
