### ISSUE TITLE
Python bug with docker container

### ISSUE THREAD

**Issue by middleagedman** [ThePhaseless/Byparr#181]
### I've completed the following steps:

- [x] Read Loop Warning on Readme
- [x] Done the troubleshooting from Readme
- [x] Checked if such issue already exists
- [x] Checked other websites with Cloudflare Turnstile

### OS

Docker

### Platform and model

Arch Linux

### Architecture

X86-64

### Describe the bug

Spun up byparr in Docker.. just see this error, although it does seem to be benign as the software still works, but wanted to let you know.

INFO:     From: 172.21.0.1 at 2025-05-25 02:57:15: https://prowlarr.servarr.com/v1/ping
/app/.venv/lib/python3.13/site-packages/pyautogui/_pyautogui_x11.py:284: SyntaxWarning: invalid escape sequence '\e'  '\e': _display.keysym_to_keycode(Xlib.XK.string_to_keysym('Escape')),

### Docker Compose config

```
    byparr:
      image: ghcr.io/thephaseless/byparr:latest
      container_name: byparr
      networks:
        - media-arr
      ports:
        - 192.168.1.9:8191:8191
      restart: unless-stopped
      shm_size: 2gb
```

### Byparr Logs

```
Using version 1.2.0

INFO:     Started server process [10]

INFO:     Waiting for application startup.

INFO:     Application startup complete.

INFO:     Uvicorn running on http://0.0.0.0:8191 (Press CTRL+C to quit)

INFO:     From: 172.21.0.1 at 2025-05-25 02:57:15: https://prowlarr.servarr.com/v1/ping

/app/.venv/lib/python3.13/site-packages/pyautogui/_pyautogui_x11.py:284: SyntaxWarning: invalid escape sequence '\e'

  '\e': _display.keysym_to_keycode(Xlib.XK.string_to_keysym('Escape')),

INFO:     127.0.0.1:53546 - "GET /health HTTP/1.1" 200 OK

INFO:     Done https://prowlarr.servarr.com/v1/ping in 6.03s
