### ISSUE TITLE
Browser crashing on RPi 5

### ISSUE THREAD

**Issue by eteache** [ThePhaseless/Byparr#93]
### I've completed the following steps:

- [x] Read Loop Warning on Readme
- [x] Done the troubleshooting from Readme
- [x] Checked if such issue already exists

### OS

Docker

### Platform and model

RPi5

### Architecture

ARM64

### Describe the bug

Just pulled today the latest image (8h ago) in my raspberry pi and used the compose.yaml from the repository but when I started the container it just shows an error and it's not usable. 

Log: [byparr.log](https://github.com/user-attachments/files/18993341/byparr.log)

**Comment by eteache** [comment]
Yesterday, I built the image directly instead of pulling it because the image wasn't tagged and couldn't be downloaded, and I still had the same problem I have today. 
Docker did tell me there was no image for my architecture, but today it had no problem with it.

**Comment by ThePhaseless** [comment]
Hi. could you try setting higher shm size or sharing it with the container to check if that's the issue?
[Source](https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot)

**Comment by eteache** [comment]
Hi. 
Tried 256m, 512m.... same results.

**Comment by ThePhaseless** [comment]
have you tried `main` branch?

**Comment by eteache** [comment]
Yep, no success. (building `main ` branch and pulling `main ` image)
The error starts the moment the docker healthcheck launches the first check.

**Comment by ThePhaseless** [comment]
Unfortunately, I do not have any raspberry pi, so I can't replicate... I will leave this open though so others can maybe help you find the issue. [Here's some info that I found](https://github.com/dgtlmoon/changedetection.io/discussions/2221)

**Comment by AmirulAndalib** [comment]
Hi,  

I'm experiencing an issue on my Raspberry Pi 4B. While restarting the device temporarily resolves the problem, I encounter the following error when using Prowlarr for the indexer captcha:  

```
root@raspberrypi:/etc/systemd/system# docker logs -f byparr
Using version unknown
INFO:     Started server process [10]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8191 (Press CTRL+C to quit)
INFO:     From: 172.18.0.11 at 2025-03-02 13:33:55: https://[prowlarr indexer]/cat/Movies/time/desc/1/
/app/.venv/lib/python3.13/site-packages/pyautogui/_pyautogui_x11.py:284: SyntaxWarning: invalid escape sequence '\e'
  '\e': _display.keysym_to_keycode(Xlib.XK.string_to_keysym('Escape')),
INFO:     Clicked captcha
INFO:     Failed https://[prowlarr indexer]/cat/Movies/time/desc/1/ in 27.15s
INFO:     172.18.0.11:57494 - "POST /v1 HTTP/1.1" 500 Internal Server Error
```

Here is my `docker-compose.yml` file:  

```yaml
services:
  byparr:
    image: ghcr.io/thephaseless/byparr:main
    container_name: byparr
    restart: unless-stopped
    ports:
      - "8191:8191"  # API port for Byparr
    environment:
      TZ: "Pacific/Auckland"     # Set timezone
      PUID: "1000"               # User ID for permissions
      PGID: "1000"               # Group ID for permissions
    networks:
      - nginx-network
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This helps when you need to resolve issues with local DNS

networks:
  nginx-network:
    external: true
```

Despite successfully clicking the captcha, the request ultimately fails, resulting in a `500 Internal Server Error`. I would greatly appreciate any insights on how to resolve this issue.  

Thanks!
